---
title: "pratice of Multiple Correspondence Analysis"
author: "ha ngoc trang"
date: "2024-05-24"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```

#### install and load packages

```{r}
install.packages("factoextra")
install.packages("FactoMineR")
install.packages("tidyverse")
install.packages("readr")
install.packages("dplyr")
install.packages("ggplot2")
```

```{r include=FALSE}
library(FactoMineR)
library(factoextra)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
```

#### load data

```{r echo=TRUE, message=TRUE}
knitr::kable(data)
#load data
data <- read_csv("data.csv")
summary(data)
```

#### rename headers

```{r echo=TRUE}
names(data)<-str_replace_all(names(data), c(" " = "." , "," = "" ))
str(data)
```

#### data manipulation (categorical variables as factors with levels)

```{r echo=TRUE}
data$BMI.Category <- gsub("Normal Weight", "Normal", data$BMI.Category)
data$BMI.Category <- factor(data$BMI.Category, levels = c("Normal","Overweight","Obese"))

data$sleep.hours <- as.factor(ifelse(data$Sleep.Duration < 7, '< 7 hours',
                                     ifelse(data$Sleep.Duration > 7, '7 - 9 hours', '7 hours')))
data <- data %>%
  mutate(Stress.Level = as.character(Stress.Level)) %>%
  mutate(Quality.of.Sleep = as.character(Quality.of.Sleep))
data$Stress.Level <- factor(data$Stress.Level,levels = c("1","2","3","4","5","6","7","8","9","10"))
data$Quality.of.Sleep <- factor(data$Quality.of.Sleep,levels = c("1","2","3","4","5","6","7","8","9","10"))

data$agecat <- as.factor(ifelse(data$Age < 31, '20 - 30',
                        ifelse(data$Age < 41, '30 - 40', 
                        ifelse(data$Age < 51, '40 - 50', '50 - 60'))))

data$bloodpressure <- as.factor(ifelse(data$Blood.Pressure %in% c("117/76","118/76","115/75","115/78","119/77","118/75"), 'normal',
                                ifelse(data$Blood.Pressure %in% c("121/79"), 'elevated', 
                                ifelse(data$Blood.Pressure %in% c("120/80","125/80","122/80","126/83","132/87","130/86","128/85","131/86","128/84","135/88","129/84","130/85","125/82"), 'high bp stage 1', 'high bp stage 2'))))
data$bloodpressure <- factor(data$bloodpressure, levels = c("normal", "elevated", "high bp stage 1", "high bp stage 2"))

data$dailysteps <- as.factor(ifelse(data$Daily.Steps < 5000, 'sedentary',
                            ifelse(data$Daily.Steps > 4999 & data$Daily.Steps < 7500, 'low active', 
                            ifelse(data$Daily.Steps > 7499 & data$Daily.Steps < 10000, 'somewhat active', 'active'))))
data$dailysteps <- factor(data$dailysteps, levels = c("sedentary","low active","somewhat active","active"))

data$heart.rate <- case_when(
  data$Gender == "Male" & data$Heart.Rate > 70 & data$Heart.Rate < 76 ~ "average",
  data$Gender == "Male" & data$Heart.Rate > 65 & data$Heart.Rate < 72 ~ "above average",
  data$Gender == "Male" & data$Heart.Rate > 74 & data$Heart.Rate < 81 ~ "below average",
  data$Gender == "Male" & data$Heart.Rate > 54 & data$Heart.Rate < 62 ~ "excellent",
  data$Gender == "Male" & data$Heart.Rate > 61 & data$Heart.Rate < 67 ~ "good",
  data$Gender == "Male" & data$Heart.Rate > 81 ~ "poor",
  data$Gender == "Female" & data$Heart.Rate > 72 & data$Heart.Rate < 77 ~ "average",
  data$Gender == "Female" & data$Heart.Rate > 68 & data$Heart.Rate < 74 ~ "above average",
  data$Gender == "Female" & data$Heart.Rate > 76 & data$Heart.Rate < 84 ~ "below average",
  data$Gender == "Female" & data$Heart.Rate > 59 & data$Heart.Rate < 65 ~ "excellent",
  data$Gender == "Female" & data$Heart.Rate > 64 & data$Heart.Rate < 69 ~ "good",
  data$Gender == "Female" & data$Heart.Rate > 83 ~ "poor")
data$heart.rate <- factor(data$heart.rate, levels = c("poor", "below average", "average", "above average","good","excellent"))

data$Sleep.Disorder <- factor(data$Sleep.Disorder, levels = c("None", "Insomnia", "Sleep Apnea"))
str(data)
```

#### subset data to run MCA

```{r}
dataMCA <- subset(data, select = c(2,4,6,8,9,13:18))
str(dataMCA)
```

#### Multiple Correspondence Analysis

```{r echo=TRUE}
res.mca <- MCA(dataMCA, quali.sup = c(1,2,8), graph = FALSE)
summary(res.mca)
head(res.mca$eig, 10)
fviz_screeplot(res.mca, addlabels = TRUE, ylim = c(0, 45))
```

#### dimdesc

```{r echo=TRUE}
res.desc <- dimdesc(res.mca, axes = c(1,2))
# Description of dimension 1
res.desc[[1]]
# Description of dimension 2
res.desc[[2]]
```

#### categories variables

```{r echo=TRUE}
var <- get_mca_var(res.mca)
var
fviz_mca_var(res.mca, choice = "mca.cor", 
             repel = TRUE, ggtheme = theme_minimal(),
             geom = c("arrow", "text"), arrow.size = 0.02, arrow.length = unit(0.1, "inches"))
```

#### coord var

```{r echo=TRUE}
var$coord
fviz_mca_var(res.mca, col.var="black", shape.var = 15,
             repel = TRUE,ggtheme = theme_minimal(),linecolor = "black")

head(round(var$coord, 2),15)
```

#### cos2

```{r echo=TRUE}
head(round(var$cos2, 2),15)
fviz_mca_var(res.mca, col.var = "cos2",  alpha.var="cos2",invisible=c("quali.sup","ind"),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE, # Avoid text overlapping
             ggtheme = theme_minimal())

library("corrplot")
corrplot(var$cos2, is.corr=FALSE,method = "number",
         tl.col = "brown",tl.cex = 0.8, tl.srt=45, number.cex = 0.5)
```

#### contrib

```{r echo=TRUE}
head(round(var$contrib, 2),15)
fviz_mca_var(res.mca, col.var = "contrib", invisible=c("quali.sup","ind"),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE, # avoid text overlapping (slow)
             ggtheme = theme_minimal())
```
